### PR TITLE
Add support for setting precision of readings.

### PR DESCRIPTION
**Pull request by adpeace**
Add a "setPrecision" method that takes values for the register indicating the precision of readings to be taken.

### CODE REVIEW

**Comment by LowPowerLab** [comment]
Thanks, tried to compile this but it's complaining:

`C:\...\Arduino\libraries\SI7021\SI7021.cpp: In member function 'void SI7021::setPrecision(byte)':
C:\...\Arduino\libraries\SI7021\SI7021.cpp:161: error: invalid conversion from 'int' to 'byte*'
C:\...\Arduino\libraries\SI7021\SI7021.cpp:161: error:   initializing argument 1 of 'void SI7021::_writeReg(byte*, int)'`

**Comment by adpeace** [comment]
Hmm - this compiled for me in the Arduino IDE just now.  However, it's clearly wrong - USER1_BYTE is an integer and _writeReg takes a pointer.  I will take a look at it tonight and post an update.  Sorry about that.

**Comment by adpeace** [comment]
I've update the branch.  Sorry again for the problem; for some reason my Arduino environment (v1.6.12 on macOS Sierra) doesn't complain, but the code was clearly wrong.  Hopefully this works in your environment also.

To test the change I added a `println` to look at the value of the user register being read before the update is made.  On the original version of the code this was coming back as `0`, presumably because the `USER1_READ` constant was being treated as a pointer and the value at that address being sent over I2C.  With the updated version of the code, this comes out as `0011 1010` which is the value the datasheet says that register should have at startup.

**Comment by LowPowerLab** [comment]
Thanks, it works!

**Pull request merged**
